#!/usr/bin/env python

CFILES = [
    'aargb.c', 'alpha.c', 'alpha3D.c', 'checker.c', 'colormat.c',
    'cube.c', 'double.c', 'fog.c', 'hello.c', 'light.c',
    'lines.c', 'material.c', 'mipmap.c', 'model.c', 'movelight.c',
    'planet.c', 'polyoff.c', 'robot.c', 'scene.c', 'smooth.c',
#    'stencil.c', 'stroke.c', 
    'texbind.c', 'texsub.c', 'torus.c', 'varray.c', 'wrap.c',
]

MMP_STUB = """// Autogenerated by makefiles.py. Do not edit.

TARGET			%(testname)s.exe
TARGETTYPE		exe

SYSTEMINCLUDE		\epoc32\include \epoc32\include\libc
SYSTEMINCLUDE		..\..\include

SOURCEPATH		..
SOURCE			%(cfilename)s

SOURCEPATH		..\..\ug
SOURCE			ug_epoc.cpp
SOURCE			uglu.c
SOURCE			ugshape.c

LIBRARY		estlib.lib
LIBRARY		euser.lib 
LIBRARY		gles_cl.lib
LIBRARY		wserv.lib ws32.lib
"""

BLD_STUB = """// Autogenerated by makefiles.py. Do not edit.

PRJ_MMPFILES
%(mmpfiles)s
"""

mmpfiles = []

for cfilename in CFILES:
    testname = cfilename.replace('.c', '')
    mmpfilename = testname + '.mmp'
    mmpfiles.append(mmpfilename)
    mmpfile = open(mmpfilename, 'wt')
    mmpfile.write(MMP_STUB % {'testname': testname, 'cfilename': cfilename})
    mmpfile.close()

bldfile = open('bld.inf', 'wt')
bldfile.write(BLD_STUB % {'mmpfiles': '\n'.join(mmpfiles)})
bldfile.close()
